services:
  backend:
    build:
      context: .          
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    networks:
      - my-network  
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    env_file:
      - .env

  ui:
    build:
      context: ./ui    
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge