services:

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - my-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - my-network
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .          
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    networks:
      - my-network  
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis

  ui:
    build:
      context: ./ui    
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge

volumes:
  redis_data:
  mongodb_data: