export enum CurrentPage {
  OTP = 'OTP',
  VERIFICATION = 'VERIFICATION',
  UPLOAD_KYC = 'UPLOAD_KYC',
  FETCHING = 'FETCHING',
  SELECT_MODE = 'SELECT_MODE',
  CHAT_MODE = 'CHAT_MODE',
  FORM_MODE = 'FORM_MODE',
  COMPLETE = 'COMPLETE',
}
